### ISSUE TITLE
添加并完善项目文档，贡献指南，使用指导

### ISSUE THREAD

**Issue by sunist-c** [alioth-center/infrastructure#15]
此路线图包括：

- [x] 1. 添加 README 文档 - #16 
- [ ] 2. 添加说明文档，预计使用 WriterSide 进行构建
- [ ] 3. 添加使用指导，预计使用 WriterSide 进行构建
- [x] 4. 添加变更日志 CHANGELOG，预计使用 git-chglog 进行自动化 - #16
